joint_state_controller:
  publish_rate: 120
  type: joint_state_controller/JointStateController

robot_teta_controllers:
  type: "velocity_controllers/JointGroupPositionController"
  joints:
    - theta1
    - theta2
    - theta3
    - theta4
    - yaw

  theta1 :
    pid: {p: 1450.0, i: 5.1, d: 50.0}
  theta2 :
    pid: {p: 1450.0, i: 5.1, d: 50.0}
  theta3 :
    pid: {p: 1450.0, i: 5.1, d: 50.0}
  theta4 :
    pid: {p: 1450.0, i: 5.1, d: 50.0}
  yaw :
    pid: {p: 1450.0, i: 5.1, d: 50.0}
