joint_state_controller:
  publish_rate: 120
  type: joint_state_controller/JointStateController

theta1_position_controller:
    type: effort_controllers/JointPositionController
    joint: theta1
    pid: {p: 1450.0, i: 5.1, d: 50.0}

theta2_position_controller:
    type: effort_controllers/JointPositionController
    joint: theta2
    pid: {p: 1450.0, i: 5.1, d: 50.0}

theta3_position_controller:
    type: effort_controllers/JointPositionController
    joint: theta3
    pid: {p: 1450.0, i: 5.1, d: 50.0}

theta4_position_controller:
    type: effort_controllers/JointPositionController
    joint: theta4
    pid: {p: 1450.0, i: 5.1, d: 50.0}

yaw_position_controller:
    type: effort_controllers/JointPositionController
    joint: yaw
    pid: {p: 1450.0, i: 5.1, d: 50.0}

gripper_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: alfa1
    pid: {p: 1450.0, i: 5.1, d: 50.0}
    
gripper_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: alfa2
    pid: {p: 1450.0, i: 5.1, d: 50.0}

gripper_3_position_controller:
    type: effort_controllers/JointPositionController
    joint: alfa3
    pid: {p: 1450.0, i: 5.1, d: 50.0}

