joint_state_controller:
  publish_rate: 120
  type: joint_state_controller/JointStateController

robot_arm_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
        - theta1
        - theta2
        - theta3
        - theta4
        #- yaw
    constraints:
        goal_time: 0.5                   # Override default
        stopped_velocity_tolerance: 0.02 # Override default
        theta1:
            trajectory: 0.05               # Not enforced if unspecified
            goal: 0.02                     # Not enforced if unspecified
        theta2:
            goal: 0.01                     # Not enforced if unspecified
        theta3:
            goal: 0.01                     # Not enforced if unspecified
        theta4:
            goal: 0.01                     # Not enforced if unspecified
        #yaw:
        #    goal: 0.01                     # Not enforced if unspecified   
    gains: # Required because we're controlling an effort interface
        theta1: {p: 1450.0, i: 5.1, d: 50.0, i_clamp: 1}
        theta2: {p: 1450.0, i: 5.1, d: 50.0, i_clamp: 1}
        theta3: {p: 1450.0, i: 5.1, d: 50.0, i_clamp: 1}
        theta4: {p: 1450.0, i: 5.1, d: 50.0, i_clamp: 1}
        #yaw: {p: 1450.0, i: 5.1, d: 50.0, i_clamp: 1}
#Controller to control end effector joints


gripper_position_controller:
    type: "effort_controllers/JointGroupPositionController"
    joints:
        - alfa1
        - alfa2
        - alfa3
    alfa1 :
        pid: {p: 5000.0, i: 5.1, d: 50.0, i_clamp: 1}
    alfa2 :
        pid: {p: 5000.0, i: 5.1, d: 50.0, i_clamp: 1}
    alfa3 :
        pid: {p: 5000.0, i: 5.1, d: 50.0, i_clamp: 1}
  
#Controller to continuously publish joint states/positions
